version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "0"
      MYSQL_ROOT_PASSWORD: "0"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8889:8080"
  jupyter:
    container_name:   notebook
#    image: jupyter/datascience-notebook
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    volumes:
      - ../notebook:/home/jovyan/work
    ports:
      - 8888:8888
    command: /bin/bash -c "start-notebook.sh --NotebookApp.token=''"
    links:
      - db
  flask:
    image: tiangolo/uwsgi-nginx-flask:python3.6
    container_name: flask_server
    volumes:
      - ../app:/app
    ports:
      - "8886:80"
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
    links:
      - db